//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Localization
{
    public static class LogViewerModule
    {
        public static readonly string Title = "Localization.LogViewerModule.Title";
    }


    public static class LogViewerView
    {
        public static readonly string Title = "Localization.LogViewerView.Title";
        public static readonly string Description = "Localization.LogViewerView.Description";
        public static readonly string OpenFile = "Localization.LogViewerView.OpenFile";
        public static readonly string Reload = "Localization.LogViewerView.Reload";
        public static readonly string FollowTail = "Localization.LogViewerView.FollowTail";
        public static readonly string JumpToTail = "Localization.LogViewerView.JumpToTail";
        public static readonly string FilePath = "Localization.LogViewerView.FilePath";
        public static readonly string FilePathWatermark = "Localization.LogViewerView.FilePathWatermark";
        public static readonly string OpenLogFileDialogTitle = "Localization.LogViewerView.OpenLogFileDialogTitle";
        public static readonly string ReadyStatus = "Localization.LogViewerView.ReadyStatus";
        public static readonly string OpeningStatus = "Localization.LogViewerView.OpeningStatus";
        public static readonly string IndexingStatus = "Localization.LogViewerView.IndexingStatus";
        public static readonly string MonitoringStatus = "Localization.LogViewerView.MonitoringStatus";
        public static readonly string EmptyFileStatus = "Localization.LogViewerView.EmptyFileStatus";
        public static readonly string FileDeletedStatus = "Localization.LogViewerView.FileDeletedStatus";
        public static readonly string LinesStatus = "Localization.LogViewerView.LinesStatus";
        public static readonly string SizeStatus = "Localization.LogViewerView.SizeStatus";
        public static readonly string TailPreviewStatus = "Localization.LogViewerView.TailPreviewStatus";
        public static readonly string OpenHint = "Localization.LogViewerView.OpenHint";
    }


}
