<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" />
		<PackageReference Include="Avalonia.AvaloniaEdit" />
		<PackageReference Include="Dapper" />
		<PackageReference Include="Dapper.AOT" />
		<PackageReference Include="Microsoft.Data.Sqlite" />
		<PackageReference Include="Prism.DryIoc.Avalonia" />
		<PackageReference Include="CodeWF.Toolkit.Core" />
    <PackageReference Include="CodeWF.Toolkit.Files" />
    <PackageReference Include="CodeWF.Toolkit.Image" />
		<PackageReference Include="CodeWF.Avalonia.Controls" />
		<PackageReference Include="CodeWF.Toolkit.EventBus" />
		<PackageReference Include="CodeWF.Avalonia.Lang" />
	</ItemGroup>

</Project>
