<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net11.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" />
		<PackageReference Include="Avalonia.AvaloniaEdit" />
		<PackageReference Include="Dapper" />
		<PackageReference Include="Dapper.AOT" />
		<PackageReference Include="Microsoft.Data.Sqlite" />
		<PackageReference Include="Prism.DryIoc.Avalonia" />
		<PackageReference Include="CodeWF.Tools" />
		<PackageReference Include="CodeWF.AvaloniaControls" />
		<PackageReference Include="CodeWF.EventBus" />
		<PackageReference Include="Lang.Avalonia.Xml" />
	</ItemGroup>

</Project>
