<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFrameworks>net9.0-windows;net10.0-windows</TargetFrameworks>
		<Nullable>enable</Nullable>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<PublishAot>true</PublishAot>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<Platforms>AnyCPU;x64;ARM32;x86</Platforms>
	</PropertyGroup>
	<PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))">
		<IsTrimmable>true</IsTrimmable>
		<PublishTrimmed>true</PublishTrimmed>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.2.5" />
		<PackageReference Include="Avalonia.Desktop" Version="11.2.5" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.5" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.5" />
		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.2.5" />
		<PackageReference Include="Avalonia.ReactiveUI" Version="11.2.5" />
		<PackageReference Include="CodeWF.EventBus" Version="3.4.5" />
		<PackageReference Include="Semi.Avalonia" Version="11.2.1.5" />
		<PackageReference Include="YY-Thunks" Version="1.1.6-Beta9" />
	</ItemGroup>
</Project>