<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net11.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);Dapper.AOT</InterceptorsPreviewNamespaces>
	</PropertyGroup>

	<ItemGroup>
		<None Include="I18n\Language.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Language.tt</DependentUpon>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Prism.DryIoc.Avalonia" />
		<PackageReference Include="ReactiveUI.Avalonia" />
		<PackageReference Include="AvaloniaEdit.TextMate" />
		<PackageReference Include="TextMateSharp.Grammars" />
		<PackageReference Include="Irihi.Ursa.Themes.Semi" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CodeWF.Core\CodeWF.Core.csproj" />
		<ProjectReference Include="..\CodeWF.Modules.ToolFramework\CodeWF.Modules.ToolFramework.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="I18n\Language.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Language.tt</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<None Update="I18n\DevelopmentModule.zh-Hant.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="I18n\DevelopmentModule.en-US.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="I18n\DevelopmentModule.ja-JP.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="I18n\Language.tt">
			<Generator>TextTemplatingFileGenerator</Generator>
			<LastGenOutput>Language.cs</LastGenOutput>
		</None>
		<None Update="I18n\DevelopmentModule.zh-CN.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
	</ItemGroup>

</Project>
