<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net11.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Prism.DryIoc.Avalonia" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CodeWF.Core\CodeWF.Core.csproj" />
		<ProjectReference Include="..\CodeWF.Modules.ToolFramework\CodeWF.Modules.ToolFramework.csproj" />
	</ItemGroup>

</Project>
