//------------------------------------------------------------------------------  
// <auto-generated>  
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------
namespace Localization
{
    public static class DevelopmentModule
    {
        public const string Title = "Localization.DevelopmentModule.Title";
    }


    public static class YamlPrettifyView
    {
        public const string Title = "Localization.YamlPrettifyView.Title";
        public const string Description = "Localization.YamlPrettifyView.Description";
        public const string RawYaml = "Localization.YamlPrettifyView.RawYaml";
        public const string PrettifiedVersionYAML = "Localization.YamlPrettifyView.PrettifiedVersionYAML";
    }


    public static class JsonPrettifyView
    {
        public const string Title = "Localization.JsonPrettifyView.Title";
        public const string Description = "Localization.JsonPrettifyView.Description";
        public const string RawJson = "Localization.JsonPrettifyView.RawJson";
        public const string PrettifiedVersionJSON = "Localization.JsonPrettifyView.PrettifiedVersionJSON";
        public const string SortKey = "Localization.JsonPrettifyView.SortKey";
        public const string IndentSize = "Localization.JsonPrettifyView.IndentSize";
    }

}


