
//------------------------------------------------------------------------------  
// <auto-generated>  
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------

namespace CodeWF.Modules.Development.I18n;

public static class Language
{
	public static readonly string YamlPrettify = "YamlPrettify";
	public static readonly string Development = "Development";
	public static readonly string YamlPrettifyDescription = "YamlPrettifyDescription";
	public static readonly string RawYaml = "RawYaml";
	public static readonly string PrettifiedVersionYAML = "PrettifiedVersionYAML";
	public static readonly string SortKey = "SortKey";
	public static readonly string IndentSize = "IndentSize";
	public static readonly string JsonPrettify = "JsonPrettify";
	public static readonly string JsonPrettifyDescription = "JsonPrettifyDescription";
	public static readonly string RawJson = "RawJson";
	public static readonly string PrettifiedVersionJSON = "PrettifiedVersionJSON";
	public static readonly string CompressFiles = "CompressFiles";
	public static readonly string DecompressionFiles = "DecompressionFiles";
	public static readonly string SelectCompressFiles = "SelectCompressFiles";
	public static readonly string SaveCompressedFile = "SaveCompressedFile";
	public static readonly string CompressFileExceptionTitle = "CompressFileExceptionTitle";
	public static readonly string CompressFileExceptionContent = "CompressFileExceptionContent";
	public static readonly string SelectDecompressionFile = "SelectDecompressionFile";
	public static readonly string SelectDirectory = "SelectDirectory";
	public static readonly string DecompressionFileExceptionTitle = "DecompressionFileExceptionTitle";
	public static readonly string DecompressionFileExceptionContent = "DecompressionFileExceptionContent";
}
