//------------------------------------------------------------------------------  
// <auto-generated>  
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------
namespace Localization
{
    public class DevelopmentModule
    {
        public const string Title = "Localization.DevelopmentModule.Title";
    }
}
namespace Localization
{
    public class YamlPrettifyView
    {
        public const string Title = "Localization.YamlPrettifyView.Title";
        public const string Description = "Localization.YamlPrettifyView.Description";
        public const string RawYaml = "Localization.YamlPrettifyView.RawYaml";
        public const string PrettifiedVersionYAML = "Localization.YamlPrettifyView.PrettifiedVersionYAML";
    }
}
namespace Localization
{
    public class JsonPrettifyView
    {
        public const string Title = "Localization.JsonPrettifyView.Title";
        public const string Description = "Localization.JsonPrettifyView.Description";
        public const string RawJson = "Localization.JsonPrettifyView.RawJson";
        public const string PrettifiedVersionJSON = "Localization.JsonPrettifyView.PrettifiedVersionJSON";
        public const string SortKey = "Localization.JsonPrettifyView.SortKey";
        public const string IndentSize = "Localization.JsonPrettifyView.IndentSize";
    }
}
namespace Localization
{
    public class TestView
    {
        public const string CompressFiles = "Localization.TestView.CompressFiles";
        public const string DecompressionFiles = "Localization.TestView.DecompressionFiles";
        public const string SelectCompressFiles = "Localization.TestView.SelectCompressFiles";
        public const string SaveCompressedFile = "Localization.TestView.SaveCompressedFile";
        public const string CompressFileExceptionTitle = "Localization.TestView.CompressFileExceptionTitle";
        public const string CompressFileExceptionContent = "Localization.TestView.CompressFileExceptionContent";
        public const string SelectDecompressionFile = "Localization.TestView.SelectDecompressionFile";
        public const string SelectDirectory = "Localization.TestView.SelectDirectory";
        public const string DecompressionFileExceptionTitle = "Localization.TestView.DecompressionFileExceptionTitle";
        public const string DecompressionFileExceptionContent = "Localization.TestView.DecompressionFileExceptionContent";
        public const string TimeoutAlarm = "Localization.TestView.TimeoutAlarm";
        public const string ShowAll = "Localization.TestView.ShowAll";
        public const string FilterAlarms = "Localization.TestView.FilterAlarms";
        public const string FilterNormal = "Localization.TestView.FilterNormal";
    }
}
