//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeWF.Modules.Development.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeWF.Modules.Development.I18n.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 开发 的本地化字符串。
        /// </summary>
        internal static string Localization_DevelopmentModule_Title {
            get {
                return ResourceManager.GetString("Localization.DevelopmentModule.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将JSON字符串修饰为友好的可读格式。 的本地化字符串。
        /// </summary>
        internal static string Localization_JsonPrettifyView_Description {
            get {
                return ResourceManager.GetString("Localization.JsonPrettifyView.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段缩进： 的本地化字符串。
        /// </summary>
        internal static string Localization_JsonPrettifyView_IndentSize {
            get {
                return ResourceManager.GetString("Localization.JsonPrettifyView.IndentSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式化后的Json格式： 的本地化字符串。
        /// </summary>
        internal static string Localization_JsonPrettifyView_PrettifiedVersionJSON {
            get {
                return ResourceManager.GetString("Localization.JsonPrettifyView.PrettifiedVersionJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始Json格式： 的本地化字符串。
        /// </summary>
        internal static string Localization_JsonPrettifyView_RawJson {
            get {
                return ResourceManager.GetString("Localization.JsonPrettifyView.RawJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对Key排序： 的本地化字符串。
        /// </summary>
        internal static string Localization_JsonPrettifyView_SortKey {
            get {
                return ResourceManager.GetString("Localization.JsonPrettifyView.SortKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JSON美化和格式化 的本地化字符串。
        /// </summary>
        internal static string Localization_JsonPrettifyView_Title {
            get {
                return ResourceManager.GetString("Localization.JsonPrettifyView.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压缩文件异常: {0} 的本地化字符串。
        /// </summary>
        internal static string Localization_TestView_CompressFileExceptionContent {
            get {
                return ResourceManager.GetString("Localization.TestView.CompressFileExceptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压缩文件异常 的本地化字符串。
        /// </summary>
        internal static string Localization_TestView_CompressFileExceptionTitle {
            get {
                return ResourceManager.GetString("Localization.TestView.CompressFileExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压缩文件 的本地化字符串。
        /// </summary>
        internal static string Localization_TestView_CompressFiles {
            get {
                return ResourceManager.GetString("Localization.TestView.CompressFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解压文件异常: {0} 的本地化字符串。
        /// </summary>
        internal static string Localization_TestView_DecompressionFileExceptionContent {
            get {
                return ResourceManager.GetString("Localization.TestView.DecompressionFileExceptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解压文件异常 的本地化字符串。
        /// </summary>
        internal static string Localization_TestView_DecompressionFileExceptionTitle {
            get {
                return ResourceManager.GetString("Localization.TestView.DecompressionFileExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解压文件 的本地化字符串。
        /// </summary>
        internal static string Localization_TestView_DecompressionFiles {
            get {
                return ResourceManager.GetString("Localization.TestView.DecompressionFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具开发过程中，部分功能测试 的本地化字符串。
        /// </summary>
        internal static string Localization_TestView_Description {
            get {
                return ResourceManager.GetString("Localization.TestView.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选告警 的本地化字符串。
        /// </summary>
        internal static string Localization_TestView_FilterAlarms {
            get {
                return ResourceManager.GetString("Localization.TestView.FilterAlarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选正常 的本地化字符串。
        /// </summary>
        internal static string Localization_TestView_FilterNormal {
            get {
                return ResourceManager.GetString("Localization.TestView.FilterNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存压缩文件 的本地化字符串。
        /// </summary>
        internal static string Localization_TestView_SaveCompressedFile {
            get {
                return ResourceManager.GetString("Localization.TestView.SaveCompressedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择要压缩的文件列表 的本地化字符串。
        /// </summary>
        internal static string Localization_TestView_SelectCompressFiles {
            get {
                return ResourceManager.GetString("Localization.TestView.SelectCompressFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解压后选择要保存的目录 的本地化字符串。
        /// </summary>
        internal static string Localization_TestView_SelectDecompressionFile {
            get {
                return ResourceManager.GetString("Localization.TestView.SelectDecompressionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解压后选择要保存的目录 的本地化字符串。
        /// </summary>
        internal static string Localization_TestView_SelectDirectory {
            get {
                return ResourceManager.GetString("Localization.TestView.SelectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示全部 的本地化字符串。
        /// </summary>
        internal static string Localization_TestView_ShowAll {
            get {
                return ResourceManager.GetString("Localization.TestView.ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时告警 的本地化字符串。
        /// </summary>
        internal static string Localization_TestView_TimeoutAlarm {
            get {
                return ResourceManager.GetString("Localization.TestView.TimeoutAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试 的本地化字符串。
        /// </summary>
        internal static string Localization_TestView_Title {
            get {
                return ResourceManager.GetString("Localization.TestView.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YAML美化和格式化 的本地化字符串。
        /// </summary>
        internal static string Localization_YamlPrettifyView_Description {
            get {
                return ResourceManager.GetString("Localization.YamlPrettifyView.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 美化后的Yaml格式 的本地化字符串。
        /// </summary>
        internal static string Localization_YamlPrettifyView_PrettifiedVersionYAML {
            get {
                return ResourceManager.GetString("Localization.YamlPrettifyView.PrettifiedVersionYAML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始Yaml格式 的本地化字符串。
        /// </summary>
        internal static string Localization_YamlPrettifyView_RawYaml {
            get {
                return ResourceManager.GetString("Localization.YamlPrettifyView.RawYaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将YAML字符串修饰为友好的可读格式。 的本地化字符串。
        /// </summary>
        internal static string Localization_YamlPrettifyView_Title {
            get {
                return ResourceManager.GetString("Localization.YamlPrettifyView.Title", resourceCulture);
            }
        }
    }
}
