//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeWF.Modules.Development.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeWF.Modules.Development.I18n.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Development 的本地化字符串。
        /// </summary>
        public static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indent size : 的本地化字符串。
        /// </summary>
        public static string IndentSize {
            get {
                return ResourceManager.GetString("IndentSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prettified version of your YAML 的本地化字符串。
        /// </summary>
        public static string PrettifiedVersionYAML {
            get {
                return ResourceManager.GetString("PrettifiedVersionYAML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your raw YAML 的本地化字符串。
        /// </summary>
        public static string RawYaml {
            get {
                return ResourceManager.GetString("RawYaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort keys : 的本地化字符串。
        /// </summary>
        public static string SortKey {
            get {
                return ResourceManager.GetString("SortKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YAML prettify and format 的本地化字符串。
        /// </summary>
        public static string YamlPrettify {
            get {
                return ResourceManager.GetString("YamlPrettify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prettify your YAML string into a friendly, human-readable format. 的本地化字符串。
        /// </summary>
        public static string YamlPrettifyDescription {
            get {
                return ResourceManager.GetString("YamlPrettifyDescription", resourceCulture);
            }
        }
    }
}
