//------------------------------------------------------------------------------  
// <auto-generated>  
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------
namespace Localization
{
    public static class MainModule
    {
        public static readonly string Title = "Localization.MainModule.Title";
        public static readonly string ShowMainWindow = "Localization.MainModule.ShowMainWindow";
        public static readonly string Exit = "Localization.MainModule.Exit";
    }
}
namespace Localization
{
    public static class MainWindow
    {
        public static readonly string SearchToolTip = "Localization.MainWindow.SearchToolTip";
        public static readonly string NoMorePrompts = "Localization.MainWindow.NoMorePrompts";
        public static readonly string SureExit = "Localization.MainWindow.SureExit";
        public static readonly string FindInTrayIcon = "Localization.MainWindow.FindInTrayIcon";
    }
}
namespace Localization
{
    public static class DashboardView
    {
        public static readonly string Title = "Localization.DashboardView.Title";
        public static readonly string WeChat = "Localization.DashboardView.WeChat";
        public static readonly string WeChatPublic = "Localization.DashboardView.WeChatPublic";
        public static readonly string DesiredAvailabilityNotification = "Localization.DashboardView.DesiredAvailabilityNotification";
        public static readonly string AccessToolbox = "Localization.DashboardView.AccessToolbox";
        public static readonly string MissingTool = "Localization.DashboardView.MissingTool";
    }
}
namespace Localization
{
    public static class SettingView
    {
        public static readonly string Title = "Localization.SettingView.Title";
    }
}
namespace Localization
{
    public static class CommonSettingView
    {
        public static readonly string Title = "Localization.CommonSettingView.Title";
        public static readonly string Description = "Localization.CommonSettingView.Description";
        public static readonly string Theme = "Localization.CommonSettingView.Theme";
        public static readonly string FollowingSystem = "Localization.CommonSettingView.FollowingSystem";
        public static readonly string LightMode = "Localization.CommonSettingView.LightMode";
        public static readonly string DarkMode = "Localization.CommonSettingView.DarkMode";
        public static readonly string LanguageKey = "Localization.CommonSettingView.LanguageKey";
        public static readonly string AutoOpenToolboxAtStartup = "Localization.CommonSettingView.AutoOpenToolboxAtStartup";
        public static readonly string HideTrayIconOnClose = "Localization.CommonSettingView.HideTrayIconOnClose";
        public static readonly string DisplayPromptWhenClosing = "Localization.CommonSettingView.DisplayPromptWhenClosing";
        public static readonly string TurnOn = "Localization.CommonSettingView.TurnOn";
        public static readonly string TurnOff = "Localization.CommonSettingView.TurnOff";
    }
}
namespace Localization
{
    public static class UpdateLogView
    {
        public static readonly string Title = "Localization.UpdateLogView.Title";
        public static readonly string Description = "Localization.UpdateLogView.Description";
    }
}
namespace Localization
{
    public static class AboutView
    {
        public static readonly string Title = "Localization.AboutView.Title";
        public static readonly string Description = "Localization.AboutView.Description";
    }
}
