//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeWF.Toolbox.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeWF.Toolbox.I18n.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 This project is only used for learning purposes. 的本地化字符串。
        /// </summary>
        internal static string Localization_AboutView_Description {
            get {
                return ResourceManager.GetString("Localization.AboutView.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string Localization_AboutView_Title {
            get {
                return ResourceManager.GetString("Localization.AboutView.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aquatic 的本地化字符串。
        /// </summary>
        internal static string Localization_CommonSettingView_Aquatic {
            get {
                return ResourceManager.GetString("Localization.CommonSettingView.Aquatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically open the toolbox at startup 的本地化字符串。
        /// </summary>
        internal static string Localization_CommonSettingView_AutoOpenToolboxAtStartup {
            get {
                return ResourceManager.GetString("Localization.CommonSettingView.AutoOpenToolboxAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        internal static string Localization_CommonSettingView_Dark {
            get {
                return ResourceManager.GetString("Localization.CommonSettingView.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow the system 的本地化字符串。
        /// </summary>
        internal static string Localization_CommonSettingView_Default {
            get {
                return ResourceManager.GetString("Localization.CommonSettingView.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The interface style setting 的本地化字符串。
        /// </summary>
        internal static string Localization_CommonSettingView_Description {
            get {
                return ResourceManager.GetString("Localization.CommonSettingView.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desert 的本地化字符串。
        /// </summary>
        internal static string Localization_CommonSettingView_Desert {
            get {
                return ResourceManager.GetString("Localization.CommonSettingView.Desert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display a prompt when closing the window 的本地化字符串。
        /// </summary>
        internal static string Localization_CommonSettingView_DisplayPromptWhenClosing {
            get {
                return ResourceManager.GetString("Localization.CommonSettingView.DisplayPromptWhenClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dusk 的本地化字符串。
        /// </summary>
        internal static string Localization_CommonSettingView_Dusk {
            get {
                return ResourceManager.GetString("Localization.CommonSettingView.Dusk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide the tray icon when closing the window 的本地化字符串。
        /// </summary>
        internal static string Localization_CommonSettingView_HideTrayIconOnClose {
            get {
                return ResourceManager.GetString("Localization.CommonSettingView.HideTrayIconOnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Localization_CommonSettingView_LanguageKey {
            get {
                return ResourceManager.GetString("Localization.CommonSettingView.LanguageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose a language 的本地化字符串。
        /// </summary>
        internal static string Localization_CommonSettingView_LanguagePlaceholderText {
            get {
                return ResourceManager.GetString("Localization.CommonSettingView.LanguagePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        internal static string Localization_CommonSettingView_Light {
            get {
                return ResourceManager.GetString("Localization.CommonSettingView.Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Night sky 的本地化字符串。
        /// </summary>
        internal static string Localization_CommonSettingView_NightSky {
            get {
                return ResourceManager.GetString("Localization.CommonSettingView.NightSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        internal static string Localization_CommonSettingView_Theme {
            get {
                return ResourceManager.GetString("Localization.CommonSettingView.Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose a theme 的本地化字符串。
        /// </summary>
        internal static string Localization_CommonSettingView_ThemePlaceholderText {
            get {
                return ResourceManager.GetString("Localization.CommonSettingView.ThemePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Settings 的本地化字符串。
        /// </summary>
        internal static string Localization_CommonSettingView_Title {
            get {
                return ResourceManager.GetString("Localization.CommonSettingView.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn off 的本地化字符串。
        /// </summary>
        internal static string Localization_CommonSettingView_TurnOff {
            get {
                return ResourceManager.GetString("Localization.CommonSettingView.TurnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn on 的本地化字符串。
        /// </summary>
        internal static string Localization_CommonSettingView_TurnOn {
            get {
                return ResourceManager.GetString("Localization.CommonSettingView.TurnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access the online toolbox 的本地化字符串。
        /// </summary>
        internal static string Localization_DashboardView_AccessToolbox {
            get {
                return ResourceManager.GetString("Localization.DashboardView.AccessToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything you want is available. If not, please let us know. 的本地化字符串。
        /// </summary>
        internal static string Localization_DashboardView_DesiredAvailabilityNotification {
            get {
                return ResourceManager.GetString("Localization.DashboardView.DesiredAvailabilityNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There&apos;s no tool I want... 的本地化字符串。
        /// </summary>
        internal static string Localization_DashboardView_MissingTool {
            get {
                return ResourceManager.GetString("Localization.DashboardView.MissingTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Homepage 的本地化字符串。
        /// </summary>
        internal static string Localization_DashboardView_Title {
            get {
                return ResourceManager.GetString("Localization.DashboardView.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author&apos;s WeChat ID 的本地化字符串。
        /// </summary>
        internal static string Localization_DashboardView_WeChat {
            get {
                return ResourceManager.GetString("Localization.DashboardView.WeChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow WeChat official account 的本地化字符串。
        /// </summary>
        internal static string Localization_DashboardView_WeChatPublic {
            get {
                return ResourceManager.GetString("Localization.DashboardView.WeChatPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit the application directly 的本地化字符串。
        /// </summary>
        internal static string Localization_ExitOptionView_DirectToClose {
            get {
                return ResourceManager.GetString("Localization.ExitOptionView.DirectToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide to tray icon 的本地化字符串。
        /// </summary>
        internal static string Localization_ExitOptionView_HideTrayIcon {
            get {
                return ResourceManager.GetString("Localization.ExitOptionView.HideTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the close operation: 的本地化字符串。
        /// </summary>
        internal static string Localization_ExitOptionView_Message {
            get {
                return ResourceManager.GetString("Localization.ExitOptionView.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remember my choice 的本地化字符串。
        /// </summary>
        internal static string Localization_ExitOptionView_RememberMyChoice {
            get {
                return ResourceManager.GetString("Localization.ExitOptionView.RememberMyChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string Localization_MainModule_Exit {
            get {
                return ResourceManager.GetString("Localization.MainModule.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show main window 的本地化字符串。
        /// </summary>
        internal static string Localization_MainModule_ShowMainWindow {
            get {
                return ResourceManager.GetString("Localization.MainModule.ShowMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toolbox of Code World Workshop 的本地化字符串。
        /// </summary>
        internal static string Localization_MainModule_Title {
            get {
                return ResourceManager.GetString("Localization.MainModule.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can find me on the tray icon! 的本地化字符串。
        /// </summary>
        internal static string Localization_MainWindow_FindInTrayIcon {
            get {
                return ResourceManager.GetString("Localization.MainWindow.FindInTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No more prompts 的本地化字符串。
        /// </summary>
        internal static string Localization_MainWindow_NoMorePrompts {
            get {
                return ResourceManager.GetString("Localization.MainWindow.NoMorePrompts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search what you want 的本地化字符串。
        /// </summary>
        internal static string Localization_MainWindow_SearchToolTip {
            get {
                return ResourceManager.GetString("Localization.MainWindow.SearchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to exit? 的本地化字符串。
        /// </summary>
        internal static string Localization_MainWindow_SureExit {
            get {
                return ResourceManager.GetString("Localization.MainWindow.SureExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string Localization_SettingView_Title {
            get {
                return ResourceManager.GetString("Localization.SettingView.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This document meticulously records the evolution of the toolbox. Every significant version upgrade, feature enhancement, and bug fix is presented here, enabling users to have a clear understanding of the toolbox&apos;s development and track its progress. 的本地化字符串。
        /// </summary>
        internal static string Localization_UpdateLogView_Description {
            get {
                return ResourceManager.GetString("Localization.UpdateLogView.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Log 的本地化字符串。
        /// </summary>
        internal static string Localization_UpdateLogView_Title {
            get {
                return ResourceManager.GetString("Localization.UpdateLogView.Title", resourceCulture);
            }
        }
    }
}
