namespace CodeWF.Modules.AI.Models;

using System.Collections.Generic;

public class LanguageList
{
    public static List<string> Languages { get; } =
    [
        "Arabic (Israel)", // 阿拉伯语（以色列)
        "Arabic (Egypt)", // 阿拉伯语（埃及)
        "Chinese Simplified", // 中文简体
        "Chinese Traditional", // 中文繁体
        "Chinese (Hong Kong)", // 中文（香港)
        "Dutch (Netherlands)", // 荷兰语（荷兰)
        "Dutch (Belgium)", // 荷兰语（比利时)
        "English (United States)", // 英语（美国)
        "English (Australia)", // 英语（澳大利亚)
        "English (Canada)", // 英语（加拿大)
        "English (India)", // 英语（印度)
        "English (Ireland)", // 英语（爱尔兰)
        "English (New Zealand)", // 英语（新西兰)
        "English (Singapore)", // 英语（新加坡)
        "English (South Africa)", // 英语（南非)
        "English (United Kingdom)", // 英语（英国)
        "French (France)", // 法语（法国)
        "French (Belgium)", // 法语（比利时)
        "French (Canada)", // 法语（加拿大)
        "French (Switzerland)", // 法语（瑞士)
        "German (Germany)", // 德语（德国)
        "German (Liechtenstein)", // 德语（列支敦士登)
        "German (Austria)", // 德语（奥地利)
        "German (Switzerland)", // 德语（瑞士)
        "Italian (Italy)", // 意大利语（意大利)
        "Italian (Switzerland)", // 意大利语（瑞士)
        "Portuguese (Brazil)", // 葡萄牙语（巴西）
        "Portuguese (Portugal)", // 葡萄牙语（葡萄牙)
        "Spanish (Spain)", // 西班牙语（西班牙)
        "Spanish (United States)", // 西班牙语（美国)
        "Bengali (Bangladesh)", // 孟加拉语（孟加拉国)
        "Bengali (India)", // 孟加拉语（印度)
        "Croatian (Croatia)", // 克罗地亚语（克罗地亚)
        "Czech (Czech Republic)", // 捷克语（捷克共和国)
        "Danish (Denmark)", // 丹麦语（丹麦)
        "Greek (Greece)", // 希腊语（希腊)
        "Hebrew (Israel)", // 希伯来语（以色列)
        "Hindi (India)", // 印地语（印度)
        "Hungarian (Hungary)", // 匈牙利语（匈牙利)
        "Indonesian (Indonesia)", // 印度尼西亚语（印度尼西亚)
        "Japanese (Japan)", // 日语（日本)
        "Korean (South Korea)", // 韩语（韩国)
        "Malay (Malaysia)", // 马来语（马来西亚)
        "Persian (Iran)", // 波斯语（伊朗)
        "Polish (Poland)", // 波兰语（波兰)
        "Romanian (Romania)", // 罗马尼亚语（罗马尼亚)
        "Russian (Russia)", // 俄罗斯语（俄罗斯)
        "Serbian (Serbia)", // 塞尔维亚语（塞尔维亚)
        "Swedish (Sweden)", // 瑞典语（瑞典)
        "Thai (Thailand)", // 泰语（泰国)
        "Turkish (Turkey)", // 土耳其语（土耳其)
        "Urdu (Pakistan)", // 乌尔都语（巴基斯坦)
        "Vietnamese (Vietnam)", // 越南语（越南)
        "Catalan (Spain)", // 加泰隆语（西班牙)
        "Latvian (Latvia)", // 拉脱维亚语（拉脱维亚)
        "Lithuanian (Lithuania)", // 立陶宛语（立陶宛)
        "Norwegian (Norway)", // 挪威语（挪威)
        "Slovak (Slovakia)", // 斯洛伐克语（斯洛伐克)
        "Slovenian (Slovenia)", // 斯洛文尼亚语（斯洛文尼亚)
        "Bulgarian (Bulgaria)", // 保加利亚语（保加利亚)
        "Ukrainian (Ukraine)", // 乌克兰语（乌克兰)
        "Filipino (Philippines)", // 菲律宾语（菲律宾)
        "Finnish (Finland)", // 芬兰语（芬兰)
        "Afrikaans (South Africa)", // 南非荷兰语（南非)
        "Romansh (Switzerland)", // 罗曼什语（瑞士)
        "Burmese (Zawgyi)", // 缅甸语（民间）
        "Burmese (Paduak)", // 缅甸语（官方）
        "Khmer (Cambodia)", // 高棉语（柬埔寨)
        "Amharic (Ethiopia)", // 阿姆哈拉语（埃塞俄比亚)
        "Belarusian (Belarus)", // 白俄罗斯语（白俄罗斯)
        "Estonian (Estonia)", // 爱沙尼亚语（爱沙尼亚)
        "Swahili (Tanzania)", // 斯瓦希里语（坦桑尼亚)
        "Zulu (South Africa)", // 祖鲁语（南非)
        "Azerbaijani (Azerbaijan)", // 阿塞拜疆语（阿塞拜疆)
        "Armenian (Armenia)", // 亚美尼亚语（亚美尼亚)
        "Georgian (Georgia)", // 格鲁吉亚语（格鲁吉亚)
        "Laotian (Laos)", // 老挝语（老挝)
        "Mongolian (Mongolia)", // 蒙古语（蒙古)
        "Nepali (Nepal)", // 尼泊尔语（尼泊尔)
        "Kazakh (Kazakhstan)", // 哈萨克语（哈萨克斯坦)
        "Galician (Spain)", // 加利西亚语（西班牙)
        "Icelandic (Iceland)", // 冰岛语（冰岛)
        "Kannada (India)", // 卡纳达语（印度)
        "Kyrgyz (Kyrgyzstan)", // 吉尔吉斯语（吉尔吉斯斯坦)
        "Malayalam (India)", // 马拉雅拉姆语（印度)
        "Marathi (India)", // 马拉地语（印度)
        "Tamil (India)", // 泰米尔语（印度)
        "Macedonian (Macedonia)", // 马其顿语（北马其顿)
        "Telugu (India)", // 泰卢固语（印度)
        "Uzbek (Uzbekistan)", // 乌兹别克语（乌兹别克斯坦)
        "Basque (Spain)", // 巴斯克语（西班牙)
        "Sinhala (Sri Lanka)"
    ];
}