<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFrameworks>net9.0;net9.0-windows;net10.0;net10.0-windows</TargetFrameworks>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>logo.ico</ApplicationIcon>
		<Nullable>enable</Nullable>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<AssemblyName>codewf</AssemblyName>
		<!-- 禁用自动生成程序集属性 -->
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Platforms>AnyCPU;x64;x86</Platforms>
	</PropertyGroup>
	<PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0-windows'))">
		<IsTrimmable>true</IsTrimmable>
		<PublishTrimmed>true</PublishTrimmed>
	</PropertyGroup>
	<PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net10.0-windows'))">
		<IsTrimmable>true</IsTrimmable>
		<PublishTrimmed>true</PublishTrimmed>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Include="..\..\GlobalAssemblies\GlobalAssembly.cs" Link="GlobalAssembly.cs" />
	</ItemGroup>
	<ItemGroup>
		<TrimmerRootDescriptor Include="Roots.xml" />
		<Content Include="logo.ico" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" />
		<PackageReference Include="VC-LTL" Version="5.2.2" />
		<PackageReference Include="YY-Thunks" Version="1.1.8-Beta4" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\CodeWF.Toolbox\CodeWF.Toolbox.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\..\UpdateLog.md" Pack="true" PackagePath="">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>