<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFrameworks>net11.0;net11.0-windows</TargetFrameworks>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>logo.ico</ApplicationIcon>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<AssemblyName>codewf</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<WindowsSupportedOSPlatformVersion>6.1</WindowsSupportedOSPlatformVersion>
		<TargetPlatformMinVersion>6.1</TargetPlatformMinVersion>
	</PropertyGroup>

	<PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net11.0-windows'))">
		<IsTrimmable>true</IsTrimmable>
		<PublishTrimmed>true</PublishTrimmed>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Include="..\..\GlobalAssemblies\GlobalAssembly.cs" Link="GlobalAssembly.cs" />
	</ItemGroup>
	<ItemGroup>
		<TrimmerRootDescriptor Include="Roots.xml" />
		<Content Include="logo.ico" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Avalonia.Desktop" />
		<PackageReference Condition="'$(Configuration)' == 'Debug'" Include="AvaloniaUI.DiagnosticsSupport" />
		<PackageReference Include="VC-LTL" />
		<PackageReference Include="YY-Thunks" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\CodeWF.Toolbox\CodeWF.Toolbox.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\..\UpdateLog.md" Pack="true" PackagePath="">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
