//------------------------------------------------------------------------------  
// <auto-generated>  
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------
namespace Localization
{
    public static class XmlTranslatorManager
    {
        public static readonly string Title = "Localization.XmlTranslatorManager.Title";
    }
}
namespace Localization
{
    public static class ManageXMLFilesView
    {
        public static readonly string Title = "Localization.ManageXMLFilesView.Title";
        public static readonly string Description = "Localization.ManageXMLFilesView.Description";
    }
}
namespace Localization
{
    public static class MergeXMLFilesView
    {
        public static readonly string Title = "Localization.MergeXMLFilesView.Title";
        public static readonly string Description = "Localization.MergeXMLFilesView.Description";
    }
}
