//------------------------------------------------------------------------------  
// <auto-generated>  
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------
namespace Localization
{
    public static class XmlTranslatorManager
    {
        public static readonly string Title = "Localization.XmlTranslatorManager.Title";
    }
}
namespace Localization
{
    public static class MergeXmlFilesView
    {
        public static readonly string Title = "Localization.MergeXmlFilesView.Title";
        public static readonly string Description = "Localization.MergeXmlFilesView.Description";
        public static readonly string SelectLanguageDirectory = "Localization.MergeXmlFilesView.SelectLanguageDirectory";
        public static readonly string InputMergedXmlFileName = "Localization.MergeXmlFilesView.InputMergedXmlFileName";
        public static readonly string MergeFiles = "Localization.MergeXmlFilesView.MergeFiles";
        public static readonly string NoLanguageFilesTitle = "Localization.MergeXmlFilesView.NoLanguageFilesTitle";
        public static readonly string NoLanguageFilesContent = "Localization.MergeXmlFilesView.NoLanguageFilesContent";
        public static readonly string WrongNewXmlFileNameTitle = "Localization.MergeXmlFilesView.WrongNewXmlFileNameTitle";
        public static readonly string WrongNewXmlFileNameContent = "Localization.MergeXmlFilesView.WrongNewXmlFileNameContent";
        public static readonly string MergeXmlFilesExceptionTitle = "Localization.MergeXmlFilesView.MergeXmlFilesExceptionTitle";
        public static readonly string MergeXmlFilesExceptionContent = "Localization.MergeXmlFilesView.MergeXmlFilesExceptionContent";
        public static readonly string ReadXmlFilesExceptionTitle = "Localization.MergeXmlFilesView.ReadXmlFilesExceptionTitle";
        public static readonly string ReadXmlFilesExceptionContent = "Localization.MergeXmlFilesView.ReadXmlFilesExceptionContent";
    }
}
namespace Localization
{
    public static class ManageXmlFilesView
    {
        public static readonly string Title = "Localization.ManageXmlFilesView.Title";
        public static readonly string Description = "Localization.ManageXmlFilesView.Description";
    }
}
