<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFrameworks>net11.0;net11.0-windows</TargetFrameworks>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>..\..\logo.ico</ApplicationIcon>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<WindowsSupportedOSPlatformVersion>6.1</WindowsSupportedOSPlatformVersion>
		<TargetPlatformMinVersion>6.1</TargetPlatformMinVersion>
	</PropertyGroup>

	<PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net11.0-windows'))">
		<IsTrimmable>true</IsTrimmable>
		<PublishTrimmed>true</PublishTrimmed>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
		<AvaloniaResource Include="..\..\logo.svg" Link="logo.svg" />
		<AvaloniaResource Include="..\..\logo.png" Link="logo.png" />
		<AvaloniaResource Include="..\..\logo.ico" Link="logo.ico" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Include="..\..\GlobalAssemblies\GlobalAssembly.cs" Link="GlobalAssembly.cs" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="I18n\Language.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Language.tt</DependentUpon>
	  </None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" />
		<PackageReference Include="Avalonia.Desktop" />
		<PackageReference Include="CodeWF.AvaloniaControls.ProDataGrid.Themes" />
		<PackageReference Include="Semi.Avalonia" />
		<PackageReference Include="Irihi.Ursa.PrismExtension" />
		<PackageReference Include="Irihi.Ursa.Themes.Semi" />
		<PackageReference Include="Prism.Avalonia" />
		<PackageReference Include="Prism.DryIoc.Avalonia" />
		<PackageReference Include="ReactiveUI.Avalonia" />
		<PackageReference Include="VC-LTL" />
		<PackageReference Include="YY-Thunks" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\CodeWF.Controls\CodeWF.Controls.csproj" />
	  <ProjectReference Include="..\CodeWF.Modules.Converter\CodeWF.Modules.Converter.csproj" />
	  <ProjectReference Include="..\CodeWF.Modules.Data\CodeWF.Modules.Data.csproj" />
	  <ProjectReference Include="..\CodeWF.Modules.Development\CodeWF.Modules.Development.csproj" />
	  <ProjectReference Include="..\CodeWF.Modules.Math\CodeWF.Modules.Math.csproj" />
	  <ProjectReference Include="..\CodeWF.Modules.Measurement\CodeWF.Modules.Measurement.csproj" />
	  <ProjectReference Include="..\CodeWF.Modules.Media\CodeWF.Modules.Media.csproj" />
	  <ProjectReference Include="..\CodeWF.Modules.Network\CodeWF.Modules.Network.csproj" />
	  <ProjectReference Include="..\CodeWF.Modules.Security\CodeWF.Modules.Security.csproj" />
	  <ProjectReference Include="..\CodeWF.Modules.Text\CodeWF.Modules.Text.csproj" />
	  <ProjectReference Include="..\CodeWF.Modules.ToolFramework\CodeWF.Modules.ToolFramework.csproj" />
	  <ProjectReference Include="..\CodeWF.Modules.Web\CodeWF.Modules.Web.csproj" />
	  <ProjectReference Include="..\CodeWF.Modules.LogViewer\CodeWF.Modules.LogViewer.csproj" />
	  <ProjectReference Include="..\CodeWF.Modules.XmlTranslatorManager\CodeWF.Modules.XmlTranslatorManager.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\UpdateLog.md" Pack="true" PackagePath="">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="I18n\Language.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Language.tt</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <None Update="I18n\Language.tt">
	    <Generator>TextTemplatingFileGenerator</Generator>
	    <LastGenOutput>Language.cs</LastGenOutput>
	  </None>
	  <None Update="I18n\*.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <TargetPath>I18n\$(AssemblyName)\%(Filename)%(Extension)</TargetPath>
	  </None>
	  <None Update="Assets\Fonts\NotoSansSC-OFL.txt">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <TargetPath>Licenses\NotoSansSC-OFL.txt</TargetPath>
	  </None>
	</ItemGroup>
</Project>
