<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net11.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<!-- 禁用自动生成程序集属性 -->
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Include="..\..\GlobalAssemblies\GlobalAssembly.cs" Link="GlobalAssembly.cs" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="I18n\Language.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Language.tt</DependentUpon>
	  </None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" />
		<!--Condition below keeps diagnostics support out of Release output.-->
		<PackageReference Condition="'$(Configuration)' == 'Debug'" Include="AvaloniaUI.DiagnosticsSupport" />
		<PackageReference Include="Semi.Avalonia" />
		<PackageReference Include="Irihi.Ursa.PrismExtension" />
		<PackageReference Include="Irihi.Ursa.Themes.Semi" />
		<PackageReference Include="Prism.Avalonia" />
		<PackageReference Include="Prism.DryIoc.Avalonia" />
		<PackageReference Include="ReactiveUI.Avalonia" />
		<PackageReference Include="Semi.Avalonia.AvaloniaEdit" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\CodeWF.Controls\CodeWF.Controls.csproj" />
	  <ProjectReference Include="..\CodeWF.Modules.AI\CodeWF.Modules.AI.csproj" />
	  <ProjectReference Include="..\CodeWF.Modules.XmlTranslatorManager\CodeWF.Modules.XmlTranslatorManager.csproj" />
	  <ProjectReference Include="..\CodeWF.Modules.Converter\CodeWF.Modules.Converter.csproj" />
	  <ProjectReference Include="..\CodeWF.Modules.Development\CodeWF.Modules.Development.csproj" />
	  <ProjectReference Include="..\CodeWF.Modules.LogViewer\CodeWF.Modules.LogViewer.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="I18n\Language.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Language.tt</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <None Update="I18n\Language.tt">
	    <Generator>TextTemplatingFileGenerator</Generator>
	    <LastGenOutput>Language.cs</LastGenOutput>
	  </None>
	  <None Update="I18n\MainModule.en-US.xml">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="I18n\MainModule.ja-JP.xml">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="I18n\MainModule.zh-Hant.xml">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="I18n\MainModule.zh-CN.xml">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>
