<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net9.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Platforms>AnyCPU;x64;ARM32;x86</Platforms>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<InvariantGlobalization>true</InvariantGlobalization>
		<WindowsSupportedOSPlatformVersion>5.1</WindowsSupportedOSPlatformVersion>
		<SupportWinXP>true</SupportWinXP>
		<PublishAot>true</PublishAot>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM32'">
	  <InvariantGlobalization>true</InvariantGlobalization>
	  <WindowsSupportedOSPlatformVersion>5.1</WindowsSupportedOSPlatformVersion>
	  <SupportWinXP>true</SupportWinXP>
	  <PublishAot>true</PublishAot>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="CodeWF.NetWeaver" Version="2.0.0.1" />
		<PackageReference Include="Dapper" Version="2.1.66" />
		<PackageReference Include="Dapper.AOT" Version="1.0.48" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
		<PackageReference Include="VC-LTL" Version="5.2.2" />
	</ItemGroup>
</Project>