
//------------------------------------------------------------------------------  
// <auto-generated>  
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------

namespace CodeWF.Modules.AI.I18n;

public static class Language
{
	public static readonly string AI = "AI";
	public static readonly string AskBot = "AskBot";
	public static readonly string AskBotDescription = "AskBotDescription";
	public static readonly string PolyTranslate = "PolyTranslate";
	public static readonly string PolyTranslateDescription = "PolyTranslateDescription";
	public static readonly string Title2Slug = "Title2Slug";
	public static readonly string Title2SlugDescription = "Title2SlugDescription";
}
