//------------------------------------------------------------------------------  
// <auto-generated>  
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------
namespace Localization
{
    public static class ConverterModule
    {
        public static readonly string Title = "Localization.ConverterModule.Title";
    }
}
namespace Localization
{
    public static class DateTimeConverterView
    {
        public static readonly string Title = "Localization.DateTimeConverterView.Title";
        public static readonly string Description = "Localization.DateTimeConverterView.Description";
    }
}
namespace Localization
{
    public static class JsonToYamlView
    {
        public static readonly string Title = "Localization.JsonToYamlView.Title";
        public static readonly string Description = "Localization.JsonToYamlView.Description";
        public static readonly string RawJson = "Localization.JsonToYamlView.RawJson";
        public static readonly string AfterYaml = "Localization.JsonToYamlView.AfterYaml";
        public static readonly string Copy = "Localization.JsonToYamlView.Copy";
        public static readonly string Clear = "Localization.JsonToYamlView.Clear";
    }
}
namespace Localization
{
    public static class YamlToJsonView
    {
        public static readonly string Title = "Localization.YamlToJsonView.Title";
        public static readonly string Description = "Localization.YamlToJsonView.Description";
        public static readonly string RawYaml = "Localization.YamlToJsonView.RawYaml";
        public static readonly string AfterJson = "Localization.YamlToJsonView.AfterJson";
        public static readonly string Copy = "Localization.YamlToJsonView.Copy";
        public static readonly string Clear = "Localization.YamlToJsonView.Clear";
    }
}
namespace Localization
{
    public static class ImageToIconView
    {
        public static readonly string Title = "Localization.ImageToIconView.Title";
        public static readonly string ChoiceSourceImageDescription = "Localization.ImageToIconView.ChoiceSourceImageDescription";
        public static readonly string ChoiceSourceImageDialogTitle = "Localization.ImageToIconView.ChoiceSourceImageDialogTitle";
        public static readonly string DestImageSize = "Localization.ImageToIconView.DestImageSize";
        public static readonly string MergeGenerateButtonContent = "Localization.ImageToIconView.MergeGenerateButtonContent";
        public static readonly string SeparateGenerateButtonContent = "Localization.ImageToIconView.SeparateGenerateButtonContent";
        public static readonly string MemoTitle = "Localization.ImageToIconView.MemoTitle";
        public static readonly string MemoContent1 = "Localization.ImageToIconView.MemoContent1";
        public static readonly string MemoContent2 = "Localization.ImageToIconView.MemoContent2";
    }
}
