
//------------------------------------------------------------------------------  
// <auto-generated>  
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------

namespace CodeWF.Modules.Converter.I18n;

public static class Language
{
	public static readonly string Converter = "Converter";
	public static readonly string DateTimeConverter = "DateTimeConverter";
	public static readonly string DateTimeFormatConversion = "DateTimeFormatConversion";
}
