//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeWF.Modules.Converter.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeWF.Modules.Converter.I18n.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Converter 的本地化字符串。
        /// </summary>
        internal static string Localization_ConverterModule_Title {
            get {
                return ResourceManager.GetString("Localization.ConverterModule.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_ConvertButtonContent {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.ConvertButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert to Unix Timestamp 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_ConvertToTimestampLabel {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.ConvertToTimestampLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current Unix timestamp (Unix timestamp) is: 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_CurrentTimestampLabel {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.CurrentTimestampLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time (Year/Month/Day Hour:Minute:Second) 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_DateTimeFormatLabel {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.DateTimeFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert dates and times into various formats 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_Description {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Milliseconds 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_MillisecondsLabel {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.MillisecondsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RefreshButtonContent 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_RefreshButtonContent {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.RefreshButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seconds 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_SecondLabel {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.SecondLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_StartButtonContent {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.StartButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_StopButtonContent {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.StopButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unix Timestamp (Unix timestamp) 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_TimetampLabel {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.TimetampLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date Time Converter 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_Title {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image files (formats: png, jpg, jpeg, ico, webp) 的本地化字符串。
        /// </summary>
        internal static string Localization_ImageToIconView_ChoiceSourceImageDescription {
            get {
                return ResourceManager.GetString("Localization.ImageToIconView.ChoiceSourceImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the image to convert 的本地化字符串。
        /// </summary>
        internal static string Localization_ImageToIconView_ChoiceSourceImageDialogTitle {
            get {
                return ResourceManager.GetString("Localization.ImageToIconView.ChoiceSourceImageDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Size 的本地化字符串。
        /// </summary>
        internal static string Localization_ImageToIconView_DestImageSize {
            get {
                return ResourceManager.GetString("Localization.ImageToIconView.DestImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ICO files can generally be used for web page logos and application logos. 的本地化字符串。
        /// </summary>
        internal static string Localization_ImageToIconView_MemoContent1 {
            get {
                return ResourceManager.GetString("Localization.ImageToIconView.MemoContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When using ICO files on web pages, generally rename the generated ICO file to favicon.ico, place it in the root directory of the website, and add the following code inside the head tag of the page: 的本地化字符串。
        /// </summary>
        internal static string Localization_ImageToIconView_MemoContent2 {
            get {
                return ResourceManager.GetString("Localization.ImageToIconView.MemoContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string Localization_ImageToIconView_MemoTitle {
            get {
                return ResourceManager.GetString("Localization.ImageToIconView.MemoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge and Generate ICO Icons 的本地化字符串。
        /// </summary>
        internal static string Localization_ImageToIconView_MergeGenerateButtonContent {
            get {
                return ResourceManager.GetString("Localization.ImageToIconView.MergeGenerateButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate ICO Icons Separately 的本地化字符串。
        /// </summary>
        internal static string Localization_ImageToIconView_SeparateGenerateButtonContent {
            get {
                return ResourceManager.GetString("Localization.ImageToIconView.SeparateGenerateButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image to ICO Icon 的本地化字符串。
        /// </summary>
        internal static string Localization_ImageToIconView_Title {
            get {
                return ResourceManager.GetString("Localization.ImageToIconView.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Converted Yaml format: 的本地化字符串。
        /// </summary>
        internal static string Localization_JsonToYamlView_AfterYaml {
            get {
                return ResourceManager.GetString("Localization.JsonToYamlView.AfterYaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string Localization_JsonToYamlView_Clear {
            get {
                return ResourceManager.GetString("Localization.JsonToYamlView.Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string Localization_JsonToYamlView_Copy {
            get {
                return ResourceManager.GetString("Localization.JsonToYamlView.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JSON to YAML Converter 的本地化字符串。
        /// </summary>
        internal static string Localization_JsonToYamlView_Description {
            get {
                return ResourceManager.GetString("Localization.JsonToYamlView.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original Json format: 的本地化字符串。
        /// </summary>
        internal static string Localization_JsonToYamlView_RawJson {
            get {
                return ResourceManager.GetString("Localization.JsonToYamlView.RawJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert JSON to YAML online. 的本地化字符串。
        /// </summary>
        internal static string Localization_JsonToYamlView_Title {
            get {
                return ResourceManager.GetString("Localization.JsonToYamlView.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Car Relocation QR Code Immediately 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_CreateButtonContent {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.CreateButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to generate QR code 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_CreateErrorMessage {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.CreateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan QR Code to Relocate Car 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_DefaultInputTitle {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.DefaultInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan to contact the car owner or make a call 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_DefaultSubTitlePrefix {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.DefaultSubTitlePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Used to generate car relocation QR codes 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_Description {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Subtitle 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_EnableSubTitle {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.EnableSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Car relocation notification phone number 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_InputPhoneNumber {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.InputPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Car relocation prompt text (keep it concise) 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_InputTitle {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.InputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter information before clicking generate 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_NeedInputTip {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.NeedInputTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview car relocation QR code URL 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_PreviewNuoCheUrl {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.PreviewNuoCheUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please generate the car relocation QR code first 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_SaveNoQrCodeMessage {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.SaveNoQrCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_SaveNotificationTitle {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.SaveNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save the car relocation QR code image 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_SaveQrCodeErrorMessage {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.SaveQrCodeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PNG Image 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_SaveQrCodeFileFormat {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.SaveQrCodeFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Car Relocation QR Code Image 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_SaveQrCodeFileTitle {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.SaveQrCodeFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Car relocation QR code image has been saved 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_SaveQrCodeSuccessMessage {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.SaveQrCodeSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_SaveQrCodeSuccessTitle {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.SaveQrCodeSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Car Relocation QR Code Generator 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_Title {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Converted Json format: 的本地化字符串。
        /// </summary>
        internal static string Localization_YamlToJsonView_AfterJson {
            get {
                return ResourceManager.GetString("Localization.YamlToJsonView.AfterJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string Localization_YamlToJsonView_Clear {
            get {
                return ResourceManager.GetString("Localization.YamlToJsonView.Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string Localization_YamlToJsonView_Copy {
            get {
                return ResourceManager.GetString("Localization.YamlToJsonView.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use this online converter to convert YAML to JSON. 的本地化字符串。
        /// </summary>
        internal static string Localization_YamlToJsonView_Description {
            get {
                return ResourceManager.GetString("Localization.YamlToJsonView.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original YAML format: 的本地化字符串。
        /// </summary>
        internal static string Localization_YamlToJsonView_RawYaml {
            get {
                return ResourceManager.GetString("Localization.YamlToJsonView.RawYaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YAML to JSON Converter 的本地化字符串。
        /// </summary>
        internal static string Localization_YamlToJsonView_Title {
            get {
                return ResourceManager.GetString("Localization.YamlToJsonView.Title", resourceCulture);
            }
        }
    }
}
