//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeWF.Modules.Converter.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeWF.Modules.Converter.I18n.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 转换器 的本地化字符串。
        /// </summary>
        internal static string Localization_ConverterModule_Title {
            get {
                return ResourceManager.GetString("Localization.ConverterModule.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_ConvertButtonContent {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.ConvertButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换成Unix时间戳 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_ConvertToTimestampLabel {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.ConvertToTimestampLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前的Unix时间戳(Unix timestamp)是: 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_CurrentTimestampLabel {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.CurrentTimestampLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 (年/月/日 时:分:秒) 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_DateTimeFormatLabel {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.DateTimeFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将日期和时间转换为各种不同的格式 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_Description {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 毫秒 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_MillisecondsLabel {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.MillisecondsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RefreshButtonContent 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_RefreshButtonContent {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.RefreshButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_SecondLabel {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.SecondLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_StartButtonContent {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.StartButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_StopButtonContent {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.StopButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unix时间戳 (Unix timestamp) 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_TimetampLabel {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.TimetampLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期时间转换器 的本地化字符串。
        /// </summary>
        internal static string Localization_DateTimeConverterView_Title {
            get {
                return ResourceManager.GetString("Localization.DateTimeConverterView.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片文件（格式：png、jpg、jpeg、ico、webp） 的本地化字符串。
        /// </summary>
        internal static string Localization_ImageToIconView_ChoiceSourceImageDescription {
            get {
                return ResourceManager.GetString("Localization.ImageToIconView.ChoiceSourceImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择需要转换的图片 的本地化字符串。
        /// </summary>
        internal static string Localization_ImageToIconView_ChoiceSourceImageDialogTitle {
            get {
                return ResourceManager.GetString("Localization.ImageToIconView.ChoiceSourceImageDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标尺寸 的本地化字符串。
        /// </summary>
        internal static string Localization_ImageToIconView_DestImageSize {
            get {
                return ResourceManager.GetString("Localization.ImageToIconView.DestImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ico 文件一般可以用在网页的 logo 和应用程序的 logo。 的本地化字符串。
        /// </summary>
        internal static string Localization_ImageToIconView_MemoContent1 {
            get {
                return ResourceManager.GetString("Localization.ImageToIconView.MemoContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ico 文件用在网页，一般是把生成的 ico 文件，命名成 favicon.ico，并放到网站的根目录，然后在页面的 head 标签内加入以下代码： 的本地化字符串。
        /// </summary>
        internal static string Localization_ImageToIconView_MemoContent2 {
            get {
                return ResourceManager.GetString("Localization.ImageToIconView.MemoContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明 的本地化字符串。
        /// </summary>
        internal static string Localization_ImageToIconView_MemoTitle {
            get {
                return ResourceManager.GetString("Localization.ImageToIconView.MemoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并生成 ico 图标 的本地化字符串。
        /// </summary>
        internal static string Localization_ImageToIconView_MergeGenerateButtonContent {
            get {
                return ResourceManager.GetString("Localization.ImageToIconView.MergeGenerateButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单独生成 ico 图标 的本地化字符串。
        /// </summary>
        internal static string Localization_ImageToIconView_SeparateGenerateButtonContent {
            get {
                return ResourceManager.GetString("Localization.ImageToIconView.SeparateGenerateButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片转 ico 图标 的本地化字符串。
        /// </summary>
        internal static string Localization_ImageToIconView_Title {
            get {
                return ResourceManager.GetString("Localization.ImageToIconView.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换后的Yaml格式： 的本地化字符串。
        /// </summary>
        internal static string Localization_JsonToYamlView_AfterYaml {
            get {
                return ResourceManager.GetString("Localization.JsonToYamlView.AfterYaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        internal static string Localization_JsonToYamlView_Clear {
            get {
                return ResourceManager.GetString("Localization.JsonToYamlView.Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string Localization_JsonToYamlView_Copy {
            get {
                return ResourceManager.GetString("Localization.JsonToYamlView.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JSON到YAML转换器 的本地化字符串。
        /// </summary>
        internal static string Localization_JsonToYamlView_Description {
            get {
                return ResourceManager.GetString("Localization.JsonToYamlView.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始Json格式： 的本地化字符串。
        /// </summary>
        internal static string Localization_JsonToYamlView_RawJson {
            get {
                return ResourceManager.GetString("Localization.JsonToYamlView.RawJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线转换将JSON转换为YAML。 的本地化字符串。
        /// </summary>
        internal static string Localization_JsonToYamlView_Title {
            get {
                return ResourceManager.GetString("Localization.JsonToYamlView.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即生成挪车二维码 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_CreateButtonContent {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.CreateButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成二维码失败 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_CreateErrorMessage {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.CreateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫码挪车 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_DefaultInputTitle {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.DefaultInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫码联系车主或拨打电话 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_DefaultSubTitlePrefix {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.DefaultSubTitlePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于生成挪车二维码 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_Description {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加小标题 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_EnableSubTitle {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.EnableSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 挪车通知电话号码 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_InputPhoneNumber {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.InputPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 挪车提示文字（尽量简短） 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_InputTitle {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.InputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入信息再点击生成 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_NeedInputTip {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.NeedInputTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览挪车扫码网址 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_PreviewNuoCheUrl {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.PreviewNuoCheUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先生成挪车二维码 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_SaveNoQrCodeMessage {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.SaveNoQrCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_SaveNotificationTitle {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.SaveNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存挪车二维码图片失败 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_SaveQrCodeErrorMessage {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.SaveQrCodeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PNG图片 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_SaveQrCodeFileFormat {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.SaveQrCodeFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存挪车二维码图片 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_SaveQrCodeFileTitle {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.SaveQrCodeFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 挪车二维码图片已保存 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_SaveQrCodeSuccessMessage {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.SaveQrCodeSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_SaveQrCodeSuccessTitle {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.SaveQrCodeSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 挪车二维码生成器 的本地化字符串。
        /// </summary>
        internal static string Localization_NuoCheView_Title {
            get {
                return ResourceManager.GetString("Localization.NuoCheView.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换后的Json格式： 的本地化字符串。
        /// </summary>
        internal static string Localization_YamlToJsonView_AfterJson {
            get {
                return ResourceManager.GetString("Localization.YamlToJsonView.AfterJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        internal static string Localization_YamlToJsonView_Clear {
            get {
                return ResourceManager.GetString("Localization.YamlToJsonView.Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string Localization_YamlToJsonView_Copy {
            get {
                return ResourceManager.GetString("Localization.YamlToJsonView.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用此在线转换器将YAML转换为JSON。 的本地化字符串。
        /// </summary>
        internal static string Localization_YamlToJsonView_Description {
            get {
                return ResourceManager.GetString("Localization.YamlToJsonView.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始YAML格式： 的本地化字符串。
        /// </summary>
        internal static string Localization_YamlToJsonView_RawYaml {
            get {
                return ResourceManager.GetString("Localization.YamlToJsonView.RawYaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YAML到JSON转换器 的本地化字符串。
        /// </summary>
        internal static string Localization_YamlToJsonView_Title {
            get {
                return ResourceManager.GetString("Localization.YamlToJsonView.Title", resourceCulture);
            }
        }
    }
}
